### ISSUE TITLE
messing formatting

### ISSUE THREAD

**Issue by hriships** [jokeyrhyme/eclipse-formatter-profiles#1]
Its not working really well in my case. Autoformatting still screwing code formatting.
I'm missing something?

**Comment by jokeyrhyme** [comment]
Yeah, I've given up on Eclipse, sorry. I could never get this perfect, and I just gave up.

**Comment by jokeyrhyme** [comment]
If you know of a fork that does this better, let me know and I'll update the README to point there instead.

**Comment by jokeyrhyme** [comment]
I've updated the README to indicate that this project is abandoned.
